mutation ModifyBrand($data: BrandModifyInputType!) {
  modifyBrand(data: $data) {
    ... on BrandNameTakenError {
      takenMessage: message
    }
    ... on Brand {
      id
      name
      industry
      size
    }
  }
}
